In [1]:
import ee

In [3]:
ee.Authenticate()

Successfully saved authorization token.

In [2]:
ee.Initialize()

In [4]:
from src.geometries import id_to_ee, all_pastures, gdf_from_df
from src.data_sampling import times_series_pixels_of_area
from src.data_preprocessing import landsat

ndvi = landsat.select('NDVI')
SR_langum = id_to_ee(all_pastures,2)

ndvi_TS_SR_langum2 = times_series_pixels_of_area(SR_langum,ndvi)
ndvi_TS_SR_langum2 = gdf_from_df(ndvi_TS_SR_langum2)

In [5]:
ndvi_TS_SR_langum2

,NDVI,time,id,lon,lat,Timestamp,Year,Month,Day,DOY,geometry
0,0.076392,408040795443,1_1_1_1_2_LT04_029029_19821206,-96.994688,44.242025,1982-12-06 16:39:55.443,1982,12,6,340,POINT (-96.99469 44.24203)
1,0.064255,408040795443,1_1_1_1_2_LT04_029029_19821206,-96.996575,44.241788,1982-12-06 16:39:55.443,1982,12,6,340,POINT (-96.99657 44.24179)
2,0.064176,408040795443,1_1_1_1_2_LT04_029029_19821206,-96.996199,44.241782,1982-12-06 16:39:55.443,1982,12,6,340,POINT (-96.99620 44.24178)
3,0.050926,408040795443,1_1_1_1_2_LT04_029029_19821206,-96.995824,44.241775,1982-12-06 16:39:55.443,1982,12,6,340,POINT (-96.99582 44.24178)
4,0.050926,408040795443,1_1_1_1_2_LT04_029029_19821206,-96.995449,44.241769,1982-12-06 16:39:55.443,1982,12,6,340,POINT (-96.99545 44.24177)
...,...,...,...,...,...,...,...,...,...,...,...
37744,0.365762,1689527459403,2_LC09_029029_20230716,-96.995513,44.239879,2023-07-16 17:10:59.403,2023,7,16,197,POINT (-96.99551 44.23988)
37745,0.366861,1689527459403,2_LC09_029029_20230716,-96.995137,44.239873,2023-07-16 17:10:59.403,2023,7,16,197,POINT (-96.99514 44.23987)
37746,0.350136,1689527459403,2_LC09_029029_20230716,-96.994762,44.239866,2023-07-16 17:10:59.403,2023,7,16,197,POINT (-96.99476 44.23987)
37747,0.349180,1689527459403,2_LC09_029029_20230716,-96.997024,44.239636,2023-07-16 17:10:59.403,2023,7,16,197,POINT (-96.99702 44.23964)
37748,0.349893,1689527459403,2_LC09_029029_20230716,-96.997033,44.239366,2023-07-16 17:10:59.403,2023,7,16,197,POINT (-96.99703 44.23937)